[[rules]]
expr = "cpu.percent > 10"
tags = ["agent1"]
matchMax = 4
alarmMax = 3
mails = ["a@qq.com"]

[[rules]]
expr = "mem.percent > 20"
tags = ["agent2"]
matchMax = 4
alarmMax = 3
mails = ["a@qq.com"]
